<header class="template-page-head reveal">
  <div><p class="eyebrow">Template / <?= e($title) ?></p><h1><?= e($title) ?></h1><p><?= e($description) ?></p></div>
  <div class="viewport-controls" role="group" aria-label="Largura da demonstração"><button class="is-active" data-viewport="desktop">Desktop</button><button data-viewport="tablet">Tablet</button><button data-viewport="mobile">Mobile</button></div>
</header>
<section class="template-stage reveal" data-template-stage="<?= e($product) ?>">
  <div class="browser-bar"><span><i></i><i></i><i></i></span><div>https://<?= e($product) ?>.3eb.site</div><b><?= icon('external',15) ?></b></div>
  <div class="template-viewport" data-template-viewport="desktop">
    <?php if ($product === 'admin'): ?>
      <div class="mock-app mock-admin"><aside><img src="/assets/image/logo/logo-symbol-brand.png" alt=""><nav><b></b><b class="on"></b><b></b><b></b><b></b></nav><i></i></aside><main><header><div><small>Admin / Visão geral</small><strong>Controle da plataforma</strong></div><span class="mock-avatar">TS</span></header><section class="mock-body"><div class="mock-title"><div><h3>Bom dia, Tiao.</h3><p>Acompanhe o ecossistema em tempo real.</p></div><button>Novo projeto</button></div><div class="mock-kpis"><article><span>Projetos</span><strong>24</strong><small>+12%</small></article><article><span>Usuários</span><strong>1.248</strong><small>+8%</small></article><article><span>Disponibilidade</span><strong>99,98%</strong><small>Estável</small></article></div><div class="mock-panels"><article><h4>Atividade</h4><div class="mock-bars"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></article><article><h4>Ambientes</h4><p><i class="green"></i>Portal <b>Online</b></p><p><i class="green"></i>Docs <b>Online</b></p><p><i class="amber"></i>Sandbox <b>Build</b></p></article></div></section></main></div>
    <?php elseif ($product === 'portal'): ?>
      <div class="mock-app mock-portal"><aside><img src="/assets/image/logo/logo-symbol-brand.png" alt=""><nav><b class="on"></b><b></b><b></b><b></b></nav><div class="mini-profile"><i></i><span></span></div></aside><main><header><small>Meu portal</small><div><span></span><span class="mock-avatar">TS</span></div></header><section class="mock-body"><p class="mock-eyebrow">Jornada Threeebs</p><h3>Continue de onde parou.</h3><p>Você concluiu 3 de 5 etapas da configuração inicial.</p><div class="mock-progress"><i></i></div><div class="mock-journey"><article class="done"><span>✓</span><div><strong>Crie sua conta</strong><small>Concluído</small></div></article><article class="done"><span>✓</span><div><strong>Complete o perfil</strong><small>Concluído</small></div></article><article class="current"><span>3</span><div><strong>Conecte seu projeto</strong><small>Próximo passo</small></div><button>Continuar</button></article></div></section></main></div>
    <?php elseif ($product === 'docs'): ?>
      <div class="mock-app mock-docs"><aside><img src="/assets/image/logo/logo-lockup-white.png" alt=""><label><span>⌕</span>Buscar documentação</label><nav><small>Introdução</small><b class="on">Começando</b><b>Instalação</b><small>Fundamentos</small><b>Design tokens</b><b>Temas</b><b>Componentes</b></nav></aside><main><header><span>Docs / Fundamentos / Tokens</span><i></i></header><article><p class="mock-eyebrow">Fundamentos</p><h3>Design tokens</h3><p>Tokens são decisões de design representadas como dados. Eles conectam a identidade visual aos produtos.</p><h4>Token semântico</h4><pre><code>:root { --3eb-action-primary: var(--3eb-mint-500); --3eb-text-primary: var(--3eb-cloud-50); }</code></pre><h4>Como utilizar</h4><p>Componentes devem consumir nomes semânticos em vez de valores primitivos.</p></article><aside class="mock-toc"><small>Nesta página</small><b>Token semântico</b><b>Como utilizar</b><b>Temas</b></aside></main></div>
    <?php elseif ($product === 'community'): ?>
      <div class="mock-app mock-community"><aside><img src="/assets/image/logo/logo-symbol-brand.png" alt=""><nav><b class="on"></b><b></b><b></b><b></b></nav><i></i></aside><main><header><div><small>Comunidade</small><strong>Discussões</strong></div><button>Novo tópico</button></header><section class="mock-body"><div class="community-feed"><article><div class="mock-avatar">LM</div><div><span><strong>Lucas Martins</strong><small>há 12 min</small></span><h3>Como vocês organizam tokens entre projetos?</h3><p>Estou pensando em separar os valores primitivos dos semânticos…</p><footer><span>♡ 18</span><span>◯ 7 respostas</span><b>Design System</b></footer></div></article><article><div class="mock-avatar alt">AC</div><div><span><strong>Ana Costa</strong><small>há 1 h</small></span><h3>Compartilhando meu primeiro template</h3><p>Adaptei o shell do Portal para um projeto pessoal.</p><footer><span>♡ 31</span><span>◯ 12 respostas</span><b>Showcase</b></footer></div></article></div><aside><h4>Tópicos em alta</h4><p><b>#</b> design-system <span>42</span></p><p><b>#</b> php <span>28</span></p><p><b>#</b> projetos <span>19</span></p></aside></section></main></div>
    <?php else: ?>
      <div class="mock-auth"><section><img src="/assets/image/logo/logo-lockup-white.png" alt="Threeebs"><div><p class="mock-eyebrow">Bem-vindo de volta</p><h3>Entre na sua conta.</h3><p>Acesse seus projetos e continue sua jornada.</p></div><small>Threeebs :3 · 2026</small></section><main><form><h3>Entrar</h3><p>Informe suas credenciais para continuar.</p><label>E-mail<input type="email" value="tiao@3eb.site"></label><label>Senha<input type="password" value="password123"></label><div><label><input type="checkbox" checked> Lembrar de mim</label><a>Esqueci a senha</a></div><button type="button">Entrar</button><span>Não tem uma conta? <a>Começar agora</a></span></form></main></div>
    <?php endif; ?>
  </div>
</section>
<section class="template-notes reveal"><article><span><?= icon('layout',21) ?></span><div><h3>Responsivo</h3><p>Composição adaptada desde 320px até monitores ultrawide.</p></div></article><article><span><?= icon('palette',21) ?></span><div><h3>Tematizável</h3><p>Claro e escuro consomem o mesmo contrato semântico.</p></div></article><article><span><?= icon('accessibility',21) ?></span><div><h3>Acessível</h3><p>Semântica, foco, contraste e teclado desde a base.</p></div></article></section>

